[workspace]
resolver = "3"
members = [
  "kernel",
  "common",
  "userland/shell",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# Removed [build] and [target] sections, move them to kernel/Cargo.toml